[DS-40] 사장님 Controller 추가 & 회원 가입 Api 추가
jaemisam-a/dangol-sonnim-backend pull request #17
Opened 2023-02-15 20:11 UTC by rnjstmdals6

## Goals
- 사장님 회원가입을 위한 컨트롤러와 REST API 를 추가합니다

## Implements
- [x] SignupRequestDto 기반으로 회원 가입 진행
- [x] 회원가입 테스트 실시 

## Related Issue 
[- https://dangol-sonnim.atlassian.net/browse/DS-39?atlOrigin=eyJpIjoiMmU3ZjVjNmYxY2ExNGRkYzgwMGMwZmM0OTM4MmY2ODciLCJwIjoiaiJ9](https://dangol-sonnim.atlassian.net/browse/DS-40?atlOrigin=eyJpIjoiNTVmNzdmMWRiMDNjNDlmNTllZTZiMzM2YmQ2M2UyMmUiLCJwIjoiaiJ9)

2023-02-16 16:01 UTC, Hyeonziii commented on src/main/java/com/dangol/dangolsonnimbackend/boss/controller/BossController.java
> +    public ResponseEntity<Void> signup(@RequestBody BossSignupRequestDTO dto) {
user 회원가입도 있기 때문에 bossSignup이라거나 정확하게 명시할 수 있는 이름이면 더 좋을듯 한데 어떠신가요!

2023-02-16 16:10 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/boss/controller/BossController.java
> +    public ResponseEntity<Void> signup(@RequestBody BossSignupRequestDTO dto) {
현지님 작성법도 좋은 것 같습니다!

클래스가 서로 분리되어있어서 
보스라는 클래스 안에서 signup 이라는 api가 존재할 경우
사장님과 관련된 회원가입 api라는 것을 파악할 수 있지 않을까요!?

유저 로그인과 보스 로그인 기능이 거의 동일하다고 봐도 무방한데, 일관성을 위해서
signup 으로 통일해서 표현해도 나쁘지 않을 것 같다라고 생각하는데 어떠신지요!?

2023-02-16 16:13 UTC, Hyeonziii commented on src/main/java/com/dangol/dangolsonnimbackend/boss/controller/BossController.java
> +    public ResponseEntity<Void> signup(@RequestBody BossSignupRequestDTO dto) {
넵! 사실 이런 부분은 개인 취향으로 갈릴 수 있는 문제라 
승민님이 말씀하신 것처럼 이미 클래스가 분리되어 있기 때문에 큰 문제는 없어서 signup으로 통일하여 진행하도록 할게요!

2023-02-16 16:13 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/boss/controller/BossController.java
> +    public ResponseEntity<Void> signup(@RequestBody BossSignupRequestDTO dto) {
양보해주셔서 감사합니다!

2023-02-16 17:12 UTC, y00njinuk commented on build.gradle
> +	testImplementation 'org.springframework.security:spring-security-test'
아하, 이런 테스트도 필요하군요. CSRF 토큰은 처음 들어봤네요...

2023-02-16 17:12 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/config/SecurityConfig.java
> +                .csrf();
질문이 있습니다~! 클라이언트 인증 방식에 대하여 간단하게만 설명을 들을 수 있을까요~?  csrf 보호 기능이 무엇인가요?

2023-02-16 17:12 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/controller/BossController.java
> +    public BossController(BossService bossService) {
해당 컨트롤러의 생성자도 정의한 이유가 아래와 같은 건가요?
> 하지만 유지보수성을 높여주고 선택적인 의존성 주입이 가능하기 때문에 생성자 주입이 더 권장된다고 합니다.

2023-02-16 17:12 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/controller/BossController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
POST 메서드 일 때는 상태코드가 CREATE로 반환해야하나 보군요. 저는 이러한 스펙이 어디서 정의되었는지 궁금..

2023-02-16 17:12 UTC, y00njinuk commented on src/test/java/com/dangol/dangolsonnimbackend/boss/controller/BossControllerTest.java
> +    private BossQueryRepository bossQueryRepository;
컨트롤러를 테스트하는데 테스트에 필요한 의존성 주입 대상이 Repository로 되어있군요. 저는 Service 쪽인 줄로 알고 있었거든요. 큰 차이는 없는거겠죠?

2023-02-16 17:12 UTC, y00njinuk commented on src/test/java/com/dangol/dangolsonnimbackend/boss/controller/BossControllerTest.java
> +                        .with(SecurityMockMvcRequestPostProcessors.csrf())
> SecurityMockMvcRequestPostProcessors.csrf()

혹시,, 이 메서드는 어떤 동작을 하는 건가요?

2023-02-16 17:12 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/controller/BossController.java
> +@RequestMapping("/api/v1/boss")
이런 부분은 sqush를 통해서 커밋을 더 간단하게 나타낼 수 있을 거 같습니다.

2023-02-16 17:12 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepository.java
> -    public boolean existsByBpn(String bossPhoneNumber) {
휴대폰 번호도 중복이 될 수 있어서 제거하는 건가요?

2023-02-16 17:12 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/service/impl/BossServiceImpl.java
> +            throw new BadRequestException(ErrorCodeMessage.ALREADY_EXISTS_STORE_REGISTER_NUMBER);
ㅋㅋ 드디어 적용했군요

2023-02-16 17:12 UTC, y00njinuk commented on src/test/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepositoryTest.java
> -    @Test
그래도 확실히.. 테스트 간의 의존성이 없어서 그런지 제거하기가 훨씬 간단하네요.

2023-02-16 17:12 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/dto/BossSignupRequestDTO.java
> +    @Size(min = 1, max = 8, message = "이름은 1 ~ 8자 이여야 합니다.")
이거는 다른 요구사항이 있었는건가요?

2023-02-16 17:14 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/boss/dto/BossSignupRequestDTO.java
> +    @Size(min = 1, max = 8, message = "이름은 1 ~ 8자 이여야 합니다.")
이 부분은 사실 따로 선우님께 여쭤보진 않았습니다.
예측 가능한 부분은 알아서 해달라고 하셨기 때문에
개인적으로 판단해본 결과 8글자가 적당하지 않을까 생각해서 적용해봤습니다.

2023-02-16 17:15 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/boss/service/impl/BossServiceImpl.java
> +            throw new BadRequestException(ErrorCodeMessage.ALREADY_EXISTS_STORE_REGISTER_NUMBER);
ㄷ드디어..

2023-02-16 17:15 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepository.java
> -    public boolean existsByBpn(String bossPhoneNumber) {
사장님 다 계정 시 휴대폰 번호는 중복될 수 있다고 말씀 주셔서 제거했습니다!

2023-02-16 17:16 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/boss/controller/BossController.java
> +@RequestMapping("/api/v1/boss")
좀 더 간단하게 나타낼 수 있군요! 알아보고 나중에 적용해보겠습니다!

2023-02-16 17:18 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/boss/controller/BossController.java
> +    public BossController(BossService bossService) {
넵 맞습니다!

2023-02-16 17:21 UTC, rnjstmdals6 commented on build.gradle
> +	testImplementation 'org.springframework.security:spring-security-test'
저도 몰랐는데 MockMvc 테스트 검증 시 csrf 토큰을 확인한다고 합니다. 넣지 않으면 403 에러가 뜨더라구요.

2023-02-16 17:24 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/boss/controller/BossController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
HTTP 상태 코드에 대한 표준 스펙 정의는 IETF(Internet Engineering Task Force)에서 발행한 RFC 7231 문서에서 확인할 수 있다고 합니다!


https://www.rfc-editor.org/rfc/rfc7231

2023-02-16 17:26 UTC, rnjstmdals6 commented on src/test/java/com/dangol/dangolsonnimbackend/boss/controller/BossControllerTest.java
> +    private BossQueryRepository bossQueryRepository;
생각해보니 Service 의존성 주입을 해야되겠네요.
Controller 가 repository를 의존한다면  유연성 떨어지고 서비스 계층의 의미가 없어지는 건데..
좋은 지적 감사합니다! 수정하겠습니다!

2023-02-16 17:37 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/config/SecurityConfig.java
> +                .csrf();
이 설정은 인증과정을 거치지 않고 모든 요청을 수용하기에 클라이언트 인증 방식과는 직접적인 관련이 없습니다!
이후 관련 인증이 추가 될 시 해당 인증 방식에 대한 설명을 드리도록 하겠습니다! 

Spring Security에서는 CSRF 공격 방어를 위해 CsrfToken 기반의 방어 기능을 제공합니다. 보호 기능을 활성화하면 매 요청마다 임의의 토큰이 생성되서 요청 파라미터에 함께 전달하게 되는데, 이걸 서버에서 검증하게 되면 CSRF 공격으로부터 애플리케이션을 보호할 수 있습니다.

2023-02-16 23:07 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/config/SecurityConfig.java
> +                .csrf();
아하, 클라이언트 쪽에서는 따로 보내는 정보는 없고 토큰이 생성되는거군요.

2023-02-16 23:07 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/controller/BossController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
네 감사합니다. 한 번 확인해볼게요. 200이랑 크게 차이가 없어보여서요. response body 쪽에도 데이터는 없는거죠?

2023-02-16 23:07 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/controller/BossController.java
> +@RequestMapping("/api/v1/boss")
네. force push를 잘 활용해보셔요.

2023-02-16 23:07 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepository.java
> -    public boolean existsByEmail(String email) {
이 부분이 아까 디스코드에서 얘기한 부분이군요. 근데 기존 스펙을 유지하다가 변경된 사유가 있는걸까요?

2023-02-17 07:02 UTC, Hyeonziii commented on src/main/java/com/dangol/dangolsonnimbackend/boss/dto/BossSignupRequestDTO.java
> +    @Size(min = 1, max = 8, message = "이름은 1 ~ 8자 이여야 합니다.")
@y00njinuk 해당 사항은 1~8자 제한인데 max = 10으로 작성되어 있어서 제가 승민님께 여쭤봤던 부분입니다!

2023-02-17 07:06 UTC, Hyeonziii commented on src/test/java/com/dangol/dangolsonnimbackend/boss/controller/BossControllerTest.java
> +                        .with(SecurityMockMvcRequestPostProcessors.csrf())
테스트 시에 해당 메서드를 이용하게 되면 csrf 토큰이 생성되어 403 테스트 에러를 막기 위함이 아닐까 싶은데 맞을까요!?

2023-02-17 07:07 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepository.java
> -    public boolean existsByEmail(String email) {
사장님은 다 계정을 이용할 수 있고, 사장님이 이메일을 하나만 존재할 수도 있지 않을까라고
생각해서 착각해서 변경을 했습니다만
이메일은 계정으로 사용되는 것이라 다시 중복 검사와 유니크 조건을 추가해야겠습니다 ㅠㅠ..

2023-02-17 07:08 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/boss/controller/BossController.java
> +@RequestMapping("/api/v1/boss")
감사합니다!

2023-02-17 07:09 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/boss/controller/BossController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
바디에는 데이터를 담지 않았습니다!

2023-02-17 07:39 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepository.java
> -    public boolean existsByEmail(String email) {
그 부분은 협의가 필요할 거 같군요.

2023-02-17 17:11 UTC, rnjstmdals6 commented on src/test/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepositoryTest.java
> -    @Test
맞습니다 ㅎㅎ

2023-02-17 17:11 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepository.java
> -    public boolean existsByEmail(String email) {
디코에 말씀드렸다 싶이 그렇게 맞춰 이후에 PR로 변경할 것 같습니다

2023-02-18 07:01 UTC, y00njinuk commented
이메일 중복 검사 및 엔티티 수정 후 PR을 진행하도록 하겠습니다.

2023-02-18 07:03 UTC, y00njinuk requested changes
이메일 중복 검사 및 엔티티 수정 후 PR을 진행하도록 하겠습니다.

2023-02-19 01:09 UTC, rnjstmdals6 commented on src/test/java/com/dangol/dangolsonnimbackend/boss/controller/BossControllerTest.java
> +                        .with(SecurityMockMvcRequestPostProcessors.csrf())
현지님 말씀이 맞습니다.
csrf 보호기능이 활성화된 상태에서 Test가 가능하도록 csrf 토큰을 포함하여 요청을 처리하도록 도와줍니다

2023-02-19 16:13 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/errors/enumeration/ErrorCodeMessage.java
> +    ALREADY_EXISTS_PHONE_NUMBER("이미 존재하는 휴대폰 번호입니다."),
이 에러메세지는 가게랑 손님 쪽에서도 공용으로 쓸 수 있겠군요.

2023-02-19 16:13 UTC, y00njinuk commented on src/test/java/com/dangol/dangolsonnimbackend/boss/controller/BossControllerTest.java
> +    private MockMvc mockMvc;
다른 테스트에서는 근데 mocking을 하지 않았던데 여기서만 이러한 방식으로 진행한 이유가 있을까요?
SpringBootTest는 관련된 빈을 모두 IoC에 로딩하여 필요한 기능 맞게 주입하여 테스트하기 위함으로 알고 있거든요.
그렇게 되면, 결국 integration test와 비슷한 맥락으로 진행해야 하는게 맞지않을까?라는 생각이 듭니다.

그래도, 여기서 Mock을 사용하는게 필요하시다면 SpringBootTest 어노테이션에서도 설정값을 추가하여 의도하는 바를 명확히 하는 것도 좋을 것 같아요.

2023-02-19 16:13 UTC, y00njinuk commented on src/test/java/com/dangol/dangolsonnimbackend/boss/controller/BossControllerTest.java
> +@Transactional
롤백이 안되는 케이스가 있어서 추가된건가요?

2023-02-19 16:13 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/domain/Boss.java
> +    @Column(nullable = false, unique = true)
혹시 unique가 추가된 이유가 있나요?

2023-02-19 16:13 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/errors/enumeration/ErrorCodeMessage.java
> +    ALREADY_EXISTS_PHONE_NUMBER("이미 존재하는 휴대폰 번호입니다."),
네 맞습니다!

2023-02-19 16:53 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/boss/domain/Boss.java
> +    @Column(nullable = false, unique = true)
사장님은 이제 1인 1계정이니, 휴대폰 번호 중복 또한 추가를 했습니다.

2023-02-19 16:53 UTC, rnjstmdals6 commented on src/test/java/com/dangol/dangolsonnimbackend/boss/controller/BossControllerTest.java
> +    private MockMvc mockMvc;
보통 @SpringBootTest와 @AutoConfigureMockMvc를 사용한 테스트는 스프링 부트 애플리케이션 컨텍스트를 로드하고 HTTP 요청 및 응답을 사용하여 컨트롤러를 테스트하는 통합 테스트입니다. 따라서 이러한 테스트는 대부분의 빈을 실제로 로드하고 테스트하며, 컨트롤러 빈을 목으로 대체하지 않습니다. 따라서 HTTP 요청 및 응답을 사용하여 컨트롤러를 테스트하는 것이 주요 목적이므로 MockMvc를 사용하여 컨트롤러를 테스트하는 것이 일반적입니다.

컨트롤러에서 MockMvc 를 실제 HTTP 요청을 보내지 않고 시큐리티 매서드를 통해 csrf 토큰 문제도 쉽게 해결할 수 있습니다. 따라서 코드가 더 간략해져 생산성을 높일 수 있습니다.

하지만 csrf 기능이 활성화된 컨트롤러에서 레스트 템플릿을 사용하게된다면 엔드포인트에 요청을 먼저 한번 보내서 
csrf 토큰을 쿠키를 통해 얻어오는 작업이 필요하고 해당 csrf를 또 담아 다시 요청을 해야 정상적으로 api 실행이 가능합니다. 이것은 매우 복잡하고 효율이 떨어진다고 생각합니다.

2023-02-19 16:58 UTC, rnjstmdals6 commented on src/test/java/com/dangol/dangolsonnimbackend/boss/controller/BossControllerTest.java
> +@Transactional
회원가입 api 테스트시 수행된 트랜잭션을 롤백해줘야 하기에 해당 어노테이션을 추가하였습니다.

2023-02-19 17:25 UTC, y00njinuk commented on src/test/java/com/dangol/dangolsonnimbackend/boss/controller/BossControllerTest.java
> +    private MockMvc mockMvc;
자세한 설명 감사합니다 :)

2023-02-20 03:49 UTC, y00njinuk approved these changes
고생하셨습니다 :)

2023-02-20 07:51 UTC, Hyeonziii approved these changes

2023-02-20 09:09 UTC, merged