DS-60 [사장님] 사장님 회원탈퇴 추가
jaemisam-a/dangol-sonnim-backend pull request #27
Opened 2023-02-21 17:55 UTC by rnjstmdals6

## Goals
- 로그인 된(시큐리티 컨텍스트 홀더에 등록) 사장님의 탈퇴 기능입니다.
- Delete : api/v1/boss

## Implements
- [x] BossService
- [x] BossController
- [x] BossServiceTest
- [x] BossControllerTest

## Related Issue
- https://dangol-sonnim.atlassian.net/browse/DS-60?atlOrigin=eyJpIjoiMWFiNDNkMzcwNjA4NGZiMGI1OGViYTk0NzVmOTdkZjgiLCJwIjoiaiJ9

2023-02-23 04:48 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/controller/BossController.java
> +        return ResponseEntity.status(HttpStatus.NO_CONTENT).build();
Accepted가 낫지 않을까 싶은데 생각이...

2023-02-23 04:48 UTC, y00njinuk commented on src/test/java/com/dangol/dangolsonnimbackend/boss/controller/BossControllerTest.java
> -                        .with(SecurityMockMvcRequestPostProcessors.csrf())
csrf 보호기능이 활성화된 상태에서 Test가 가능하도록 csrf 토큰을 포함하여 요청을 처리하는 목적으로 추가하셨는데 해당 기능을 off 하신 이유가 있나요?

2023-02-23 04:48 UTC, y00njinuk commented on src/test/java/com/dangol/dangolsonnimbackend/boss/controller/BossControllerTest.java
> +    BossRepository bossRepository;
사용처가 없는 변수 같은데 추가된 이유가 있을까요?

2023-02-23 06:44 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/boss/controller/BossController.java
> +        return ResponseEntity.status(HttpStatus.NO_CONTENT).build();
202 상태 코드는 서버가 클라이언트의 요청을 받아들였지만, 요청을 즉시 처리할 수 없고 이후에 비동기적으로 처리될 것임을 나타내는 것입니다.

삭제하였을 때 응답 객체가 없고 요청을 성공적으로 처리한 경우이므로 204가 적절하다고 판단하였습니다.

2023-02-23 06:44 UTC, rnjstmdals6 commented on src/test/java/com/dangol/dangolsonnimbackend/boss/controller/BossControllerTest.java
> +    BossRepository bossRepository;
여러가지 테스트를 진행하고, 이후에 지워줬어야 했는데 제가 놓친 부분인 것 같습니다.
역시 눈썰미가 좋으십니다! 👍 👍 👍

2023-02-23 06:48 UTC, rnjstmdals6 commented on src/test/java/com/dangol/dangolsonnimbackend/boss/controller/BossControllerTest.java
> -                        .with(SecurityMockMvcRequestPostProcessors.csrf())
왜 해당 라인이 삭제된 것 처럼 보이는 지 모르겠지만 off 하지 않았습니다!
FileChange 보시면 남아있는 것을 확인하실 수 있으십니다

2023-02-23 12:55 UTC, y00njinuk requested changes

2023-02-23 12:55 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/controller/BossController.java
> +        return ResponseEntity.status(HttpStatus.NO_CONTENT).build();
넵 알겠습니다.

2023-02-23 12:55 UTC, y00njinuk approved these changes

2023-02-24 02:06 UTC, Hyeonziii approved these changes
:+1:
추후 사장님 탈퇴 시 기능에는 구독권을 구매해놓은 손님이 없을 경우에만 탈퇴가 되어야 합니다!

2023-02-24 07:02 UTC, merged