DS-65 [사장님] 사장님 정보 수정 API 추가
jaemisam-a/dangol-sonnim-backend pull request #29
Opened 2023-02-21 19:49 UTC by rnjstmdals6

## Goals
- 로그인 된(시큐리티 컨텍스트 홀더에 등록) 사장님의 정보를 수정합니다
- 폰번호와 마케팅 수신정보 일부 수정 가능합니다
- PATCH : api/v1/boss

## Implements
- [x] BossController
- [x] BossControllerTest
- [x] BossService
- [x] BossServiceImpl 

## Related Issue
https://dangol-sonnim.atlassian.net/browse/DS-65?atlOrigin=eyJpIjoiY2UzZDIwZTUxYjA3NDU0ZTgzOGJjMTFiMWI3ZjBiZDUiLCJwIjoiaiJ9

2023-02-23 05:02 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/domain/Boss.java
> +        this.phoneNumber = dto.getPhoneNumber() != null ? dto.getPhoneNumber() : this.phoneNumber;
음... null 체크와 같은 validation 작업은 레이어 별로 모두 구성을 하는 것이 좋은가요?

2023-02-23 05:02 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/service/impl/BossServiceImpl.java
> +    public Boss update(String email, BossUpdateRequestDTO requestDTO){
회원 가입을 할 때도 서비스 단에서 validation을 하신 거 같았는데 수정도 여기서 validation을 한다면 작업이 구분이 되서 더 좋을 거 같은데 혹시 어떠신가요?

2023-02-23 05:02 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/controller/BossController.java
> +    public ResponseEntity<?> authenticate(@Valid @RequestBody BossSigninReqeustDTO reqeustDTO) {
@Valid 어노테이션이 추가 되었네요.. 유효성은 혹시 어떤 방식으로 확인이 되는건가요?
JSON 쪽에 필드에 데이터가 없음을 확인하는 건가요?

2023-02-23 05:02 UTC, y00njinuk commented on src/test/java/com/dangol/dangolsonnimbackend/boss/controller/BossControllerTest.java
> -                        .with(SecurityMockMvcRequestPostProcessors.csrf())
https://github.com/jaemisam-a/dangol-sonnim-backend/pull/27#discussion_r1115230922 와 같은 이유인가요?

2023-02-23 05:02 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/service/impl/BossServiceImpl.java
> +        boss.updateInfo(requestDTO);
이런 작업은 sqush와 force push로 사사삭..! 하면 깔끔하게 커밋이 정리될 거 같습니다.

2023-02-23 07:10 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/boss/controller/BossController.java
> +    public ResponseEntity<?> authenticate(@Valid @RequestBody BossSigninReqeustDTO reqeustDTO) {
DTO 쪽 유효성 검증을 진행하는 어노테이션입니다.

2023-02-23 07:10 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/boss/domain/Boss.java
> +        this.phoneNumber = dto.getPhoneNumber() != null ? dto.getPhoneNumber() : this.phoneNumber;
해당 부분은 validation 이라기 보다는
dto 에 데이터가 있으면 수정을하고 없으면 기존 값을 유지하기 위한 코드입니다.

2023-02-23 07:10 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/boss/service/impl/BossServiceImpl.java
> +        boss.updateInfo(requestDTO);
아직 깃 사용이 미숙해서 양해부탁드립니다. ㅠ
앞으로 커밋을 깔끔하게 하기위해 노력해보겠습니다!

2023-02-23 07:10 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/boss/service/impl/BossServiceImpl.java
> +    public Boss update(String email, BossUpdateRequestDTO requestDTO){
회원 가입에서 진행한 validation 은 DB에 데이터가 존재하는 지 확인하는 작업이고,
엔티티 클래스 내에 있는 update 매서드는 validation 목적이 아닌 데이터를 갱신하기 위한 코드입니다!

2023-02-23 07:14 UTC, rnjstmdals6 commented on src/test/java/com/dangol/dangolsonnimbackend/boss/controller/BossControllerTest.java
> -                        .with(SecurityMockMvcRequestPostProcessors.csrf())
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf;
를 해줌으로써 csrf 만 남겨두었습니다.

2023-02-23 12:58 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/service/impl/BossServiceImpl.java
> +    public Boss update(String email, BossUpdateRequestDTO requestDTO){
넵~ 이해하였습니다.

2023-02-23 12:58 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/controller/BossController.java
> +    public ResponseEntity<?> authenticate(@Valid @RequestBody BossSigninReqeustDTO reqeustDTO) {
음.. 어떤 동작을 하는 지 궁금했는데 한 번 찾아보도록 하겠습니다.

2023-02-23 12:59 UTC, y00njinuk approved these changes

2023-02-23 13:34 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/service/impl/BossServiceImpl.java
> +        boss.updateInfo(requestDTO);
서비스 단에서 수정한 요청 작업이 바로 엔티티에서 수행되는데 Repository에서는 작업을 수행하지 않는 이유가 있을까요?

2023-02-23 13:35 UTC, y00njinuk requested changes
몇 가지 궁금한 사항이 생겨서 답변부탁드립니다!

2023-02-23 13:37 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/boss/service/impl/BossServiceImpl.java
> +        boss.updateInfo(requestDTO);
Repository에서 어떤 작업을 수행하는 것을 말씀하시는 걸까요?

2023-02-23 13:40 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/service/impl/BossServiceImpl.java
> +        boss.updateInfo(requestDTO);
Serivce에서는 Repository에 정의된 인터페이스를 호출하여 엔티티 객체를 수정하고 저장하는 것으로 알고 있거든요.

2023-02-23 13:43 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/boss/service/impl/BossServiceImpl.java
> +        boss.updateInfo(requestDTO);
findByEmail 매서드에서 Repository에 정의된 Boss를 호출합니다. 이후 엔티티 객체를 수정합니다!

2023-02-23 13:44 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/service/impl/BossServiceImpl.java
> +        boss.updateInfo(requestDTO);
findByEmail -> boss 엔티티 객체 수정 -> save 작업 순으로 진행되는건가요?

2023-02-23 13:45 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/boss/service/impl/BossServiceImpl.java
> +        boss.updateInfo(requestDTO);
넵 맞습니다.
save를 따로 호출하지 않아도 JPA의 더티체킹으로 엔티티의 변화를 감지하여 커밋시 변경 사항으로 영속화 됩니다.

2023-02-23 14:01 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/service/impl/BossServiceImpl.java
> +        boss.updateInfo(requestDTO);
아하~! 그 부분은 이해하였어요. 

그리고.. 저는 Service에서는 Repository를 거치지 않고 엔티티에 바로 접근하는 이유가 궁금했었는데 반환값이 바로 엔티티라서 서비스 쪽에서 구현을 다 하신 거 같네요. 저 부분은 메소드 반환값이 DTO 였다면 Repository에서 처리했을 것이고..

2023-02-23 14:04 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/boss/service/impl/BossServiceImpl.java
> +        boss.updateInfo(requestDTO);
흠 죄송하지만 혹시 시간 여유 있으시다면 업데이트를 repository에서 처리하는 예시코드를 보여주실 수 있으실까요?

2023-02-23 14:59 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/service/impl/BossServiceImpl.java
> +        boss.updateInfo(requestDTO);
제가 착각했네요! 서비스 계층과 Repository 계층 사이의 데이터 교환은 Entity를 통해서 이루어지는데 제가 DTO로 생각했었던 거 같습니다 :( ㅋㅋ 스킵해주셔도 될 거 같습니다~!

2023-02-24 02:45 UTC, Hyeonziii approved these changes
:100:

2023-02-25 13:35 UTC, y00njinuk approved these changes

2023-02-25 13:50 UTC, merged