[DS-36] 사장님 Repository 추가
jaemisam-a/dangol-sonnim-backend pull request #8
Opened 2023-02-11 15:41 UTC by rnjstmdals6

## Goals
- 사장님 Entity 를 저장 및 구성을 위한 BossRepository 를 추가합니다.
- QueryDsl 기능을 사용하기 위해 BossQueryRepository 를 추가합니다
- 중복 가입 방지를 위해 이메일, 가게 등록 번호, 핸드폰 번호가 저장소에 존재 유무를 체크하는 매서드를 추가합니다.

## Implements
- [x] 중복 가입 방지 JPA 매서드를 테스트하기 위해 단위 테스트를 진행합니다.

## Related Issue 
- https://dangol-sonnim.atlassian.net/browse/DS-36?atlOrigin=eyJpIjoiNjVjMjdiOTEzNjI5NDU3YmFmNmZjNmRmODk5NmU5ZjkiLCJwIjoiaiJ9

## Notes
해당 브랜치는 [feature/DS-35-add-boss-entity] 브랜치를 기반으로 작성되었습니다.

2023-02-11 20:37 UTC, rnjstmdals6 commented
로컬에서는 테스트가 정상적으로 통과가 되는 데
빌드 시 DB 커넥션 오류가 납니다

2023-02-12 00:49 UTC, y00njinuk commented on src/test/java/com/dangol/dangolsonnimbackend/boss/repository/BossRepositoryTest.java
> +@AutoConfigureTestDatabase(replace = Replace.NONE)
> 로컬에서는 테스트가 정상적으로 통과가 되는 데 깃 액션 빌드 시 DB 커넥션 오류가 납니다

DataJpa 어노테이션 사용 시 임베디드 된 H2 데이터베이스를 사용하기 때문에 위와 같은 annotation을 추가하여 실제 MySQL 데이터베이스를 사용할 수 있게끔 해야한다고 하네요. (스프링 부트 핵심가이드 p.192~193 참조)

2023-02-12 04:41 UTC, y00njinuk commented on src/test/java/com/dangol/dangolsonnimbackend/boss/repository/BossRepositoryTest.java
> +    void whenFindById_thenReturnBoss() {
given 표시가 없네요?

2023-02-12 04:41 UTC, y00njinuk commented on src/test/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepositoryTest.java
> +    public void givenValidEmail_whenExistsByEmail_thenReturnTrue() {
여기는 given 표시가 있던데, 위에서 진행한 BossRepositoryTest에 표기에는 없네요.

2023-02-12 05:42 UTC, rnjstmdals6 commented on src/test/java/com/dangol/dangolsonnimbackend/boss/repository/BossRepositoryTest.java
> +@AutoConfigureTestDatabase(replace = Replace.NONE)
감사합니다!!

2023-02-12 05:49 UTC, rnjstmdals6 commented on src/test/java/com/dangol/dangolsonnimbackend/boss/repository/BossRepositoryTest.java
> +    void whenFindById_thenReturnBoss() {
여기 given 은 dto에 해당됩니다.
하지만 dto를 생성하는데 중복코드가 발생하기 때문에 
setup 매서드로 따로 분리하였고 해당 코드에는 dto 가 없기 때문에 given을 작성하지 않았습니다.

근데 일관성을 위해서는 given을 추가하는 편이 더 나은 것 같아보이네요.. ㅎㅎ 수정하겠습니다!!

2023-02-12 05:57 UTC, rnjstmdals6 commented on src/test/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepositoryTest.java
> +    public void givenValidEmail_whenExistsByEmail_thenReturnTrue() {
해당 메서드 내에서 Email 이라는 데이터가 주어지지만

위에서 진행한 BossRepositoryTest에서 존재하는 테스트 코드들의 given 은 setup 매서드 내에서 명시하기 때문입니다.

2023-02-12 06:12 UTC, y00njinuk commented on src/main/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepository.java
> +        Integer fetchOne = queryFactory.selectOne()
아하... QueryDSL은 이런 방식으로 쿼리를 정의하는군요.

2023-02-12 06:12 UTC, y00njinuk commented on src/test/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepositoryTest.java
> +    public void givenValidEmail_whenExistsByEmail_thenReturnTrue() {
BossRepositoryTest 는 JPA에서 제공하는 기본적인 API를 활용한 테스트이고
BossQueryRepositoryTest는 QueryDSL을 통해 직접 정의한 API를 활용한 테스트라고 이해해도 될까요?

2023-02-12 06:41 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepository.java
> +        Integer fetchOne = queryFactory.selectOne()
금방 배우실 수 있으실 겁니다!

2023-02-12 06:41 UTC, rnjstmdals6 commented on src/test/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepositoryTest.java
> +    public void givenValidEmail_whenExistsByEmail_thenReturnTrue() {
넵!

2023-02-13 14:18 UTC, y00njinuk requested changes
https://github.com/jaemisam-a/dangol-sonnim-backend/pull/8/files#diff-12847f3a2796d886d6d98904b6a903252b0de84310833b9a56ac27a088b30bb0R16 

SpringBootTest로 어노테이션 변경 부탁드립니다.

2023-02-13 14:25 UTC, Hyeonziii commented on src/main/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepository.java
> +    public boolean existsBySrn(String srn) {
String storeRegisterNumber로 변경 부탁드려요!

2023-02-13 14:25 UTC, Hyeonziii commented on src/test/java/com/dangol/dangolsonnimbackend/boss/repository/BossRepositoryTest.java
> +@DataJpaTest
SpringBootTest로 변경 부탁드려요!

2023-02-13 19:13 UTC, rnjstmdals6 commented on src/main/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepository.java
> +    public boolean existsBySrn(String srn) {
수정 완료 했습니다 감사합니다!

2023-02-13 19:13 UTC, rnjstmdals6 commented on src/test/java/com/dangol/dangolsonnimbackend/boss/repository/BossRepositoryTest.java
> +@DataJpaTest
수정했습니다!

2023-02-14 03:20 UTC, y00njinuk approved these changes

2023-02-14 08:47 UTC, Hyeonziii approved these changes

2023-02-14 09:21 UTC, merged